services:
  - type: web
    name: m00-backend
    env: docker
    plan: free
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://matrix_db_2qsn_user:4vwvRr2W8HfEMQ7R78LKUGcKPMCe16lU@dpg-d0q819buibrs73dn90r0-a.oregon-postgres.render.com:5432/matrix_db_2qsn
      - key: SECRET_KEY
        value: 4f294976b1a2a6bda9ff8a598609108e246002bf32aa6c8788da008466cc3542
      - key: ALGORITHM
        value: HS256
    dockerfilePath: Dockerfile

  - type: web
    name: m00-dashboard
    env: docker
    plan: free
    rootDir: dashboard
    autoDeploy: true
    dockerfilePath: Dockerfile

databases:
  - name: m00-db
    plan: free
    databaseName: m00_db
    user: m00_user
    region: oregon
